# Favicon
favicon: /favicon.ico

# SEO
keywords: 生活,博客

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/imeilige
  V2EX: https://www.v2ex.com/member/imeilige

# Nav menu
menu:
  Home: /archives
  About: /about
